export const Data = [
  {
    image: "images/poster 4.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 5.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 6.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 8.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 9.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 7.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },

  {
    image: "images/poster 2.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 4.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 6.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 8.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 7.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 9.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 4.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 7.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 7.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 6.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 9.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 11.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/poster 4.png",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
];
export const Data1 = [
  {
    image: "images/card 1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 3.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 4.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 5.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 6.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 7.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 8.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/card 2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
 

];
export const Data2 = [
  {
    image: "images/c1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c3.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c3.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c3.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c1.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c3.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
  {
    image: "images/c2.webp",
    title: "movie name",
    des: "Lorem ipsum dolor sit amet consectetur",
    watch: "add to watchlist",
  },
];